/**
 * What an operator is told when a semantic index no longer matches the
 * configured embedding model.
 *
 * A vector index fixes its width when it is created, so changing the
 * embedding model leaves indexes that reject every vector the new model
 * produces. Detecting that is each adapter's own business — the catalog
 * read and the physical naming differ per engine — but the *report* is
 * contract-visible and must not: every backend says the same thing in
 * the same words, and says it in the vocabulary of the API — by entity
 * type, by document property, by search scope — never by a physical
 * index name, a vendor, or a statement.
 *
 * That is why the words live here, above the adapters, and only the
 * words: nothing in this module knows how an index is found, named, or
 * dropped.
 */

/** The semantic index of one entity type. */
export function entityTypeScope(entityTypeKey: string): string {
  return `entity type '${entityTypeKey}'`;
}

/** The chunk index of one document property. */
export function documentPropertyScope(entityTypeKey: string, propertyKey: string): string {
  return `document property '${propertyKey}' on entity type '${entityTypeKey}'`;
}

/** The cross-type entity index. */
export const ALL_ENTITY_TYPES_SCOPE = "search across all entity types";

/** The saved-query description index. */
export const SAVED_QUERY_SCOPE = "saved-query descriptions";

/**
 * Report a width mismatch the caller will not repair.
 *
 * Dropping an index destroys the vectors it holds, so the startup and
 * per-type create paths only say what they found and point at the one
 * endpoint that regenerates those vectors. A mismatch report never fails
 * the ensure.
 */
export function reportWidthMismatch(
  describes: string,
  existingWidth: number,
  configuredWidth: number,
): void {
  console.warn(
    `The semantic index for ${describes} holds ${existingWidth}-dimensional ` +
      `vectors, but the configured embedding model produces ${configuredWidth}. ` +
      "Semantic search over it fails until the widths agree. Run " +
      "POST /api/ontologies/{ontologyKey}/model/rebuild-embeddings on the " +
      "ontology holding it to recreate it at the model's width and " +
      "regenerate its vectors.",
  );
}

/**
 * Announce a repair. Only the rebuild path reaches this: there the drop
 * is followed immediately by regeneration at the new width, which is
 * exactly what the operator asked for.
 */
export function reportWidthRecreate(
  describes: string,
  existingWidth: number,
  configuredWidth: number,
): void {
  console.info(
    `Recreating the semantic index for ${describes} at ${configuredWidth} ` +
      `dimensions (was ${existingWidth}) to match the configured embedding model; ` +
      "its vectors are regenerated by this rebuild.",
  );
}
